[package]
name = "blob_storage_pull"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_core = "0.3.0"
azure_sdk_storage_blob = "0.45.3"
futures = "0.3.21"
log = "0.4.17"